// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error)
	GetTasksByUser(ctx context.Context, userID uuid.UUID) ([]Task, error)
	GetUser(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
}

var _ Querier = (*Queries)(nil)
